/* eslint-disable */

// @ts-nocheck

// noinspection JSUnusedGlobalSymbols

// This file was automatically generated by TanStack Router.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { Route as rootRouteImport } from './routes/__root'
import { Route as ServicesRouteImport } from './routes/services'
import { Route as ResultsRouteImport } from './routes/results'
import { Route as RegisterRouteImport } from './routes/register'
import { Route as CoursesRouteImport } from './routes/courses'
import { Route as ContactRouteImport } from './routes/contact'
import { Route as BlogRouteImport } from './routes/blog'
import { Route as AdminRouteImport } from './routes/admin'
import { Route as AboutRouteImport } from './routes/about'
import { Route as IndexRouteImport } from './routes/index'
import { Route as ServicesIndexRouteImport } from './routes/services/index'
import { Route as BlogIndexRouteImport } from './routes/blog.index'
import { Route as ServicesVciVeterinaryAdmissionRouteImport } from './routes/services/vci-veterinary-admission'
import { Route as ServicesSheepGoatProjectReportRouteImport } from './routes/services/sheep-goat-project-report'
import { Route as ServicesPracticalExamCoachingRouteImport } from './routes/services/practical-exam-coaching'
import { Route as ServicesPoultryProjectReportRouteImport } from './routes/services/poultry-project-report'
import { Route as ServicesPolyhouseProjectsRouteImport } from './routes/services/polyhouse-projects'
import { Route as ServicesNriQuotaAdmissionRouteImport } from './routes/services/nri-quota-admission'
import { Route as ServicesKcetSeatAllocationRouteImport } from './routes/services/kcet-seat-allocation'
import { Route as ServicesInvestmentSubsidyGuidanceRouteImport } from './routes/services/investment-subsidy-guidance'
import { Route as ServicesIcarExamPrepRouteImport } from './routes/services/icar-exam-prep'
import { Route as ServicesDairyProjectReportRouteImport } from './routes/services/dairy-project-report'
import { Route as ServicesCropLoansSupportRouteImport } from './routes/services/crop-loans-support'
import { Route as ServicesAoAaoBankExamRouteImport } from './routes/services/ao-aao-bank-exam'
import { Route as ServicesAgriConsultingReportsRouteImport } from './routes/services/agri-consulting-reports'
import { Route as ServicesAgriConsultingDprRouteImport } from './routes/services/agri-consulting-dpr'
import { Route as BlogSlugRouteImport } from './routes/blog.$slug'
import { Route as AoAaoRouteImport } from './routes/ao.aao'
import { Route as AoAaoPremiumRouteImport } from './routes/ao.aao_.premium'
import { Route as AoAaoCheckoutRouteImport } from './routes/ao.aao_.checkout'
import { Route as AoAaoAuthRouteImport } from './routes/ao.aao_.auth'
import { Route as AoAaoTestTestIdRouteImport } from './routes/ao.aao_.test.$testId'
import { Route as AoAaoReportSubmissionIdRouteImport } from './routes/ao.aao_.report.$submissionId'

const ServicesRoute = ServicesRouteImport.update({
  id: '/services',
  path: '/services',
  getParentRoute: () => rootRouteImport,
} as any)
const ResultsRoute = ResultsRouteImport.update({
  id: '/results',
  path: '/results',
  getParentRoute: () => rootRouteImport,
} as any)
const RegisterRoute = RegisterRouteImport.update({
  id: '/register',
  path: '/register',
  getParentRoute: () => rootRouteImport,
} as any)
const CoursesRoute = CoursesRouteImport.update({
  id: '/courses',
  path: '/courses',
  getParentRoute: () => rootRouteImport,
} as any)
const ContactRoute = ContactRouteImport.update({
  id: '/contact',
  path: '/contact',
  getParentRoute: () => rootRouteImport,
} as any)
const BlogRoute = BlogRouteImport.update({
  id: '/blog',
  path: '/blog',
  getParentRoute: () => rootRouteImport,
} as any)
const AdminRoute = AdminRouteImport.update({
  id: '/admin',
  path: '/admin',
  getParentRoute: () => rootRouteImport,
} as any)
const AboutRoute = AboutRouteImport.update({
  id: '/about',
  path: '/about',
  getParentRoute: () => rootRouteImport,
} as any)
const IndexRoute = IndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => rootRouteImport,
} as any)
const ServicesIndexRoute = ServicesIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => ServicesRoute,
} as any)
const BlogIndexRoute = BlogIndexRouteImport.update({
  id: '/',
  path: '/',
  getParentRoute: () => BlogRoute,
} as any)
const ServicesVciVeterinaryAdmissionRoute =
  ServicesVciVeterinaryAdmissionRouteImport.update({
    id: '/vci-veterinary-admission',
    path: '/vci-veterinary-admission',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesSheepGoatProjectReportRoute =
  ServicesSheepGoatProjectReportRouteImport.update({
    id: '/sheep-goat-project-report',
    path: '/sheep-goat-project-report',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPracticalExamCoachingRoute =
  ServicesPracticalExamCoachingRouteImport.update({
    id: '/practical-exam-coaching',
    path: '/practical-exam-coaching',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPoultryProjectReportRoute =
  ServicesPoultryProjectReportRouteImport.update({
    id: '/poultry-project-report',
    path: '/poultry-project-report',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesPolyhouseProjectsRoute =
  ServicesPolyhouseProjectsRouteImport.update({
    id: '/polyhouse-projects',
    path: '/polyhouse-projects',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesNriQuotaAdmissionRoute =
  ServicesNriQuotaAdmissionRouteImport.update({
    id: '/nri-quota-admission',
    path: '/nri-quota-admission',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesKcetSeatAllocationRoute =
  ServicesKcetSeatAllocationRouteImport.update({
    id: '/kcet-seat-allocation',
    path: '/kcet-seat-allocation',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesInvestmentSubsidyGuidanceRoute =
  ServicesInvestmentSubsidyGuidanceRouteImport.update({
    id: '/investment-subsidy-guidance',
    path: '/investment-subsidy-guidance',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesIcarExamPrepRoute = ServicesIcarExamPrepRouteImport.update({
  id: '/icar-exam-prep',
  path: '/icar-exam-prep',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesDairyProjectReportRoute =
  ServicesDairyProjectReportRouteImport.update({
    id: '/dairy-project-report',
    path: '/dairy-project-report',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesCropLoansSupportRoute =
  ServicesCropLoansSupportRouteImport.update({
    id: '/crop-loans-support',
    path: '/crop-loans-support',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAoAaoBankExamRoute = ServicesAoAaoBankExamRouteImport.update({
  id: '/ao-aao-bank-exam',
  path: '/ao-aao-bank-exam',
  getParentRoute: () => ServicesRoute,
} as any)
const ServicesAgriConsultingReportsRoute =
  ServicesAgriConsultingReportsRouteImport.update({
    id: '/agri-consulting-reports',
    path: '/agri-consulting-reports',
    getParentRoute: () => ServicesRoute,
  } as any)
const ServicesAgriConsultingDprRoute =
  ServicesAgriConsultingDprRouteImport.update({
    id: '/agri-consulting-dpr',
    path: '/agri-consulting-dpr',
    getParentRoute: () => ServicesRoute,
  } as any)
const BlogSlugRoute = BlogSlugRouteImport.update({
  id: '/$slug',
  path: '/$slug',
  getParentRoute: () => BlogRoute,
} as any)
const AoAaoRoute = AoAaoRouteImport.update({
  id: '/ao/aao',
  path: '/ao/aao',
  getParentRoute: () => rootRouteImport,
} as any)
const AoAaoPremiumRoute = AoAaoPremiumRouteImport.update({
  id: '/ao/aao_/premium',
  path: '/ao/aao/premium',
  getParentRoute: () => rootRouteImport,
} as any)
const AoAaoCheckoutRoute = AoAaoCheckoutRouteImport.update({
  id: '/ao/aao_/checkout',
  path: '/ao/aao/checkout',
  getParentRoute: () => rootRouteImport,
} as any)
const AoAaoAuthRoute = AoAaoAuthRouteImport.update({
  id: '/ao/aao_/auth',
  path: '/ao/aao/auth',
  getParentRoute: () => rootRouteImport,
} as any)
const AoAaoTestTestIdRoute = AoAaoTestTestIdRouteImport.update({
  id: '/ao/aao_/test/$testId',
  path: '/ao/aao/test/$testId',
  getParentRoute: () => rootRouteImport,
} as any)
const AoAaoReportSubmissionIdRoute = AoAaoReportSubmissionIdRouteImport.update({
  id: '/ao/aao_/report/$submissionId',
  path: '/ao/aao/report/$submissionId',
  getParentRoute: () => rootRouteImport,
} as any)

export interface FileRoutesByFullPath {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/services': typeof ServicesRouteWithChildren
  '/ao/aao': typeof AoAaoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/agri-consulting-dpr': typeof ServicesAgriConsultingDprRoute
  '/services/agri-consulting-reports': typeof ServicesAgriConsultingReportsRoute
  '/services/ao-aao-bank-exam': typeof ServicesAoAaoBankExamRoute
  '/services/crop-loans-support': typeof ServicesCropLoansSupportRoute
  '/services/dairy-project-report': typeof ServicesDairyProjectReportRoute
  '/services/icar-exam-prep': typeof ServicesIcarExamPrepRoute
  '/services/investment-subsidy-guidance': typeof ServicesInvestmentSubsidyGuidanceRoute
  '/services/kcet-seat-allocation': typeof ServicesKcetSeatAllocationRoute
  '/services/nri-quota-admission': typeof ServicesNriQuotaAdmissionRoute
  '/services/polyhouse-projects': typeof ServicesPolyhouseProjectsRoute
  '/services/poultry-project-report': typeof ServicesPoultryProjectReportRoute
  '/services/practical-exam-coaching': typeof ServicesPracticalExamCoachingRoute
  '/services/sheep-goat-project-report': typeof ServicesSheepGoatProjectReportRoute
  '/services/vci-veterinary-admission': typeof ServicesVciVeterinaryAdmissionRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/ao/aao/auth': typeof AoAaoAuthRoute
  '/ao/aao/checkout': typeof AoAaoCheckoutRoute
  '/ao/aao/premium': typeof AoAaoPremiumRoute
  '/ao/aao/report/$submissionId': typeof AoAaoReportSubmissionIdRoute
  '/ao/aao/test/$testId': typeof AoAaoTestTestIdRoute
}
export interface FileRoutesByTo {
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/ao/aao': typeof AoAaoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/agri-consulting-dpr': typeof ServicesAgriConsultingDprRoute
  '/services/agri-consulting-reports': typeof ServicesAgriConsultingReportsRoute
  '/services/ao-aao-bank-exam': typeof ServicesAoAaoBankExamRoute
  '/services/crop-loans-support': typeof ServicesCropLoansSupportRoute
  '/services/dairy-project-report': typeof ServicesDairyProjectReportRoute
  '/services/icar-exam-prep': typeof ServicesIcarExamPrepRoute
  '/services/investment-subsidy-guidance': typeof ServicesInvestmentSubsidyGuidanceRoute
  '/services/kcet-seat-allocation': typeof ServicesKcetSeatAllocationRoute
  '/services/nri-quota-admission': typeof ServicesNriQuotaAdmissionRoute
  '/services/polyhouse-projects': typeof ServicesPolyhouseProjectsRoute
  '/services/poultry-project-report': typeof ServicesPoultryProjectReportRoute
  '/services/practical-exam-coaching': typeof ServicesPracticalExamCoachingRoute
  '/services/sheep-goat-project-report': typeof ServicesSheepGoatProjectReportRoute
  '/services/vci-veterinary-admission': typeof ServicesVciVeterinaryAdmissionRoute
  '/blog': typeof BlogIndexRoute
  '/services': typeof ServicesIndexRoute
  '/ao/aao/auth': typeof AoAaoAuthRoute
  '/ao/aao/checkout': typeof AoAaoCheckoutRoute
  '/ao/aao/premium': typeof AoAaoPremiumRoute
  '/ao/aao/report/$submissionId': typeof AoAaoReportSubmissionIdRoute
  '/ao/aao/test/$testId': typeof AoAaoTestTestIdRoute
}
export interface FileRoutesById {
  __root__: typeof rootRouteImport
  '/': typeof IndexRoute
  '/about': typeof AboutRoute
  '/admin': typeof AdminRoute
  '/blog': typeof BlogRouteWithChildren
  '/contact': typeof ContactRoute
  '/courses': typeof CoursesRoute
  '/register': typeof RegisterRoute
  '/results': typeof ResultsRoute
  '/services': typeof ServicesRouteWithChildren
  '/ao/aao': typeof AoAaoRoute
  '/blog/$slug': typeof BlogSlugRoute
  '/services/agri-consulting-dpr': typeof ServicesAgriConsultingDprRoute
  '/services/agri-consulting-reports': typeof ServicesAgriConsultingReportsRoute
  '/services/ao-aao-bank-exam': typeof ServicesAoAaoBankExamRoute
  '/services/crop-loans-support': typeof ServicesCropLoansSupportRoute
  '/services/dairy-project-report': typeof ServicesDairyProjectReportRoute
  '/services/icar-exam-prep': typeof ServicesIcarExamPrepRoute
  '/services/investment-subsidy-guidance': typeof ServicesInvestmentSubsidyGuidanceRoute
  '/services/kcet-seat-allocation': typeof ServicesKcetSeatAllocationRoute
  '/services/nri-quota-admission': typeof ServicesNriQuotaAdmissionRoute
  '/services/polyhouse-projects': typeof ServicesPolyhouseProjectsRoute
  '/services/poultry-project-report': typeof ServicesPoultryProjectReportRoute
  '/services/practical-exam-coaching': typeof ServicesPracticalExamCoachingRoute
  '/services/sheep-goat-project-report': typeof ServicesSheepGoatProjectReportRoute
  '/services/vci-veterinary-admission': typeof ServicesVciVeterinaryAdmissionRoute
  '/blog/': typeof BlogIndexRoute
  '/services/': typeof ServicesIndexRoute
  '/ao/aao_/auth': typeof AoAaoAuthRoute
  '/ao/aao_/checkout': typeof AoAaoCheckoutRoute
  '/ao/aao_/premium': typeof AoAaoPremiumRoute
  '/ao/aao_/report/$submissionId': typeof AoAaoReportSubmissionIdRoute
  '/ao/aao_/test/$testId': typeof AoAaoTestTestIdRoute
}
export interface FileRouteTypes {
  fileRoutesByFullPath: FileRoutesByFullPath
  fullPaths:
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/register'
    | '/results'
    | '/services'
    | '/ao/aao'
    | '/blog/$slug'
    | '/services/agri-consulting-dpr'
    | '/services/agri-consulting-reports'
    | '/services/ao-aao-bank-exam'
    | '/services/crop-loans-support'
    | '/services/dairy-project-report'
    | '/services/icar-exam-prep'
    | '/services/investment-subsidy-guidance'
    | '/services/kcet-seat-allocation'
    | '/services/nri-quota-admission'
    | '/services/polyhouse-projects'
    | '/services/poultry-project-report'
    | '/services/practical-exam-coaching'
    | '/services/sheep-goat-project-report'
    | '/services/vci-veterinary-admission'
    | '/blog/'
    | '/services/'
    | '/ao/aao/auth'
    | '/ao/aao/checkout'
    | '/ao/aao/premium'
    | '/ao/aao/report/$submissionId'
    | '/ao/aao/test/$testId'
  fileRoutesByTo: FileRoutesByTo
  to:
    | '/'
    | '/about'
    | '/admin'
    | '/contact'
    | '/courses'
    | '/register'
    | '/results'
    | '/ao/aao'
    | '/blog/$slug'
    | '/services/agri-consulting-dpr'
    | '/services/agri-consulting-reports'
    | '/services/ao-aao-bank-exam'
    | '/services/crop-loans-support'
    | '/services/dairy-project-report'
    | '/services/icar-exam-prep'
    | '/services/investment-subsidy-guidance'
    | '/services/kcet-seat-allocation'
    | '/services/nri-quota-admission'
    | '/services/polyhouse-projects'
    | '/services/poultry-project-report'
    | '/services/practical-exam-coaching'
    | '/services/sheep-goat-project-report'
    | '/services/vci-veterinary-admission'
    | '/blog'
    | '/services'
    | '/ao/aao/auth'
    | '/ao/aao/checkout'
    | '/ao/aao/premium'
    | '/ao/aao/report/$submissionId'
    | '/ao/aao/test/$testId'
  id:
    | '__root__'
    | '/'
    | '/about'
    | '/admin'
    | '/blog'
    | '/contact'
    | '/courses'
    | '/register'
    | '/results'
    | '/services'
    | '/ao/aao'
    | '/blog/$slug'
    | '/services/agri-consulting-dpr'
    | '/services/agri-consulting-reports'
    | '/services/ao-aao-bank-exam'
    | '/services/crop-loans-support'
    | '/services/dairy-project-report'
    | '/services/icar-exam-prep'
    | '/services/investment-subsidy-guidance'
    | '/services/kcet-seat-allocation'
    | '/services/nri-quota-admission'
    | '/services/polyhouse-projects'
    | '/services/poultry-project-report'
    | '/services/practical-exam-coaching'
    | '/services/sheep-goat-project-report'
    | '/services/vci-veterinary-admission'
    | '/blog/'
    | '/services/'
    | '/ao/aao_/auth'
    | '/ao/aao_/checkout'
    | '/ao/aao_/premium'
    | '/ao/aao_/report/$submissionId'
    | '/ao/aao_/test/$testId'
  fileRoutesById: FileRoutesById
}
export interface RootRouteChildren {
  IndexRoute: typeof IndexRoute
  AboutRoute: typeof AboutRoute
  AdminRoute: typeof AdminRoute
  BlogRoute: typeof BlogRouteWithChildren
  ContactRoute: typeof ContactRoute
  CoursesRoute: typeof CoursesRoute
  RegisterRoute: typeof RegisterRoute
  ResultsRoute: typeof ResultsRoute
  ServicesRoute: typeof ServicesRouteWithChildren
  AoAaoRoute: typeof AoAaoRoute
  AoAaoAuthRoute: typeof AoAaoAuthRoute
  AoAaoCheckoutRoute: typeof AoAaoCheckoutRoute
  AoAaoPremiumRoute: typeof AoAaoPremiumRoute
  AoAaoReportSubmissionIdRoute: typeof AoAaoReportSubmissionIdRoute
  AoAaoTestTestIdRoute: typeof AoAaoTestTestIdRoute
}

declare module '@tanstack/react-router' {
  interface FileRoutesByPath {
    '/services': {
      id: '/services'
      path: '/services'
      fullPath: '/services'
      preLoaderRoute: typeof ServicesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/results': {
      id: '/results'
      path: '/results'
      fullPath: '/results'
      preLoaderRoute: typeof ResultsRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/register': {
      id: '/register'
      path: '/register'
      fullPath: '/register'
      preLoaderRoute: typeof RegisterRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/courses': {
      id: '/courses'
      path: '/courses'
      fullPath: '/courses'
      preLoaderRoute: typeof CoursesRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/contact': {
      id: '/contact'
      path: '/contact'
      fullPath: '/contact'
      preLoaderRoute: typeof ContactRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/blog': {
      id: '/blog'
      path: '/blog'
      fullPath: '/blog'
      preLoaderRoute: typeof BlogRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/admin': {
      id: '/admin'
      path: '/admin'
      fullPath: '/admin'
      preLoaderRoute: typeof AdminRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/about': {
      id: '/about'
      path: '/about'
      fullPath: '/about'
      preLoaderRoute: typeof AboutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/': {
      id: '/'
      path: '/'
      fullPath: '/'
      preLoaderRoute: typeof IndexRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/services/': {
      id: '/services/'
      path: '/'
      fullPath: '/services/'
      preLoaderRoute: typeof ServicesIndexRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/': {
      id: '/blog/'
      path: '/'
      fullPath: '/blog/'
      preLoaderRoute: typeof BlogIndexRouteImport
      parentRoute: typeof BlogRoute
    }
    '/services/vci-veterinary-admission': {
      id: '/services/vci-veterinary-admission'
      path: '/vci-veterinary-admission'
      fullPath: '/services/vci-veterinary-admission'
      preLoaderRoute: typeof ServicesVciVeterinaryAdmissionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/sheep-goat-project-report': {
      id: '/services/sheep-goat-project-report'
      path: '/sheep-goat-project-report'
      fullPath: '/services/sheep-goat-project-report'
      preLoaderRoute: typeof ServicesSheepGoatProjectReportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/practical-exam-coaching': {
      id: '/services/practical-exam-coaching'
      path: '/practical-exam-coaching'
      fullPath: '/services/practical-exam-coaching'
      preLoaderRoute: typeof ServicesPracticalExamCoachingRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/poultry-project-report': {
      id: '/services/poultry-project-report'
      path: '/poultry-project-report'
      fullPath: '/services/poultry-project-report'
      preLoaderRoute: typeof ServicesPoultryProjectReportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/polyhouse-projects': {
      id: '/services/polyhouse-projects'
      path: '/polyhouse-projects'
      fullPath: '/services/polyhouse-projects'
      preLoaderRoute: typeof ServicesPolyhouseProjectsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/nri-quota-admission': {
      id: '/services/nri-quota-admission'
      path: '/nri-quota-admission'
      fullPath: '/services/nri-quota-admission'
      preLoaderRoute: typeof ServicesNriQuotaAdmissionRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/kcet-seat-allocation': {
      id: '/services/kcet-seat-allocation'
      path: '/kcet-seat-allocation'
      fullPath: '/services/kcet-seat-allocation'
      preLoaderRoute: typeof ServicesKcetSeatAllocationRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/investment-subsidy-guidance': {
      id: '/services/investment-subsidy-guidance'
      path: '/investment-subsidy-guidance'
      fullPath: '/services/investment-subsidy-guidance'
      preLoaderRoute: typeof ServicesInvestmentSubsidyGuidanceRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/icar-exam-prep': {
      id: '/services/icar-exam-prep'
      path: '/icar-exam-prep'
      fullPath: '/services/icar-exam-prep'
      preLoaderRoute: typeof ServicesIcarExamPrepRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/dairy-project-report': {
      id: '/services/dairy-project-report'
      path: '/dairy-project-report'
      fullPath: '/services/dairy-project-report'
      preLoaderRoute: typeof ServicesDairyProjectReportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/crop-loans-support': {
      id: '/services/crop-loans-support'
      path: '/crop-loans-support'
      fullPath: '/services/crop-loans-support'
      preLoaderRoute: typeof ServicesCropLoansSupportRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/ao-aao-bank-exam': {
      id: '/services/ao-aao-bank-exam'
      path: '/ao-aao-bank-exam'
      fullPath: '/services/ao-aao-bank-exam'
      preLoaderRoute: typeof ServicesAoAaoBankExamRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/agri-consulting-reports': {
      id: '/services/agri-consulting-reports'
      path: '/agri-consulting-reports'
      fullPath: '/services/agri-consulting-reports'
      preLoaderRoute: typeof ServicesAgriConsultingReportsRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/services/agri-consulting-dpr': {
      id: '/services/agri-consulting-dpr'
      path: '/agri-consulting-dpr'
      fullPath: '/services/agri-consulting-dpr'
      preLoaderRoute: typeof ServicesAgriConsultingDprRouteImport
      parentRoute: typeof ServicesRoute
    }
    '/blog/$slug': {
      id: '/blog/$slug'
      path: '/$slug'
      fullPath: '/blog/$slug'
      preLoaderRoute: typeof BlogSlugRouteImport
      parentRoute: typeof BlogRoute
    }
    '/ao/aao': {
      id: '/ao/aao'
      path: '/ao/aao'
      fullPath: '/ao/aao'
      preLoaderRoute: typeof AoAaoRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao/aao_/premium': {
      id: '/ao/aao_/premium'
      path: '/ao/aao/premium'
      fullPath: '/ao/aao/premium'
      preLoaderRoute: typeof AoAaoPremiumRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao/aao_/checkout': {
      id: '/ao/aao_/checkout'
      path: '/ao/aao/checkout'
      fullPath: '/ao/aao/checkout'
      preLoaderRoute: typeof AoAaoCheckoutRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao/aao_/auth': {
      id: '/ao/aao_/auth'
      path: '/ao/aao/auth'
      fullPath: '/ao/aao/auth'
      preLoaderRoute: typeof AoAaoAuthRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao/aao_/test/$testId': {
      id: '/ao/aao_/test/$testId'
      path: '/ao/aao/test/$testId'
      fullPath: '/ao/aao/test/$testId'
      preLoaderRoute: typeof AoAaoTestTestIdRouteImport
      parentRoute: typeof rootRouteImport
    }
    '/ao/aao_/report/$submissionId': {
      id: '/ao/aao_/report/$submissionId'
      path: '/ao/aao/report/$submissionId'
      fullPath: '/ao/aao/report/$submissionId'
      preLoaderRoute: typeof AoAaoReportSubmissionIdRouteImport
      parentRoute: typeof rootRouteImport
    }
  }
}

interface BlogRouteChildren {
  BlogSlugRoute: typeof BlogSlugRoute
  BlogIndexRoute: typeof BlogIndexRoute
}

const BlogRouteChildren: BlogRouteChildren = {
  BlogSlugRoute: BlogSlugRoute,
  BlogIndexRoute: BlogIndexRoute,
}

const BlogRouteWithChildren = BlogRoute._addFileChildren(BlogRouteChildren)

interface ServicesRouteChildren {
  ServicesAgriConsultingDprRoute: typeof ServicesAgriConsultingDprRoute
  ServicesAgriConsultingReportsRoute: typeof ServicesAgriConsultingReportsRoute
  ServicesAoAaoBankExamRoute: typeof ServicesAoAaoBankExamRoute
  ServicesCropLoansSupportRoute: typeof ServicesCropLoansSupportRoute
  ServicesDairyProjectReportRoute: typeof ServicesDairyProjectReportRoute
  ServicesIcarExamPrepRoute: typeof ServicesIcarExamPrepRoute
  ServicesInvestmentSubsidyGuidanceRoute: typeof ServicesInvestmentSubsidyGuidanceRoute
  ServicesKcetSeatAllocationRoute: typeof ServicesKcetSeatAllocationRoute
  ServicesNriQuotaAdmissionRoute: typeof ServicesNriQuotaAdmissionRoute
  ServicesPolyhouseProjectsRoute: typeof ServicesPolyhouseProjectsRoute
  ServicesPoultryProjectReportRoute: typeof ServicesPoultryProjectReportRoute
  ServicesPracticalExamCoachingRoute: typeof ServicesPracticalExamCoachingRoute
  ServicesSheepGoatProjectReportRoute: typeof ServicesSheepGoatProjectReportRoute
  ServicesVciVeterinaryAdmissionRoute: typeof ServicesVciVeterinaryAdmissionRoute
  ServicesIndexRoute: typeof ServicesIndexRoute
}

const ServicesRouteChildren: ServicesRouteChildren = {
  ServicesAgriConsultingDprRoute: ServicesAgriConsultingDprRoute,
  ServicesAgriConsultingReportsRoute: ServicesAgriConsultingReportsRoute,
  ServicesAoAaoBankExamRoute: ServicesAoAaoBankExamRoute,
  ServicesCropLoansSupportRoute: ServicesCropLoansSupportRoute,
  ServicesDairyProjectReportRoute: ServicesDairyProjectReportRoute,
  ServicesIcarExamPrepRoute: ServicesIcarExamPrepRoute,
  ServicesInvestmentSubsidyGuidanceRoute:
    ServicesInvestmentSubsidyGuidanceRoute,
  ServicesKcetSeatAllocationRoute: ServicesKcetSeatAllocationRoute,
  ServicesNriQuotaAdmissionRoute: ServicesNriQuotaAdmissionRoute,
  ServicesPolyhouseProjectsRoute: ServicesPolyhouseProjectsRoute,
  ServicesPoultryProjectReportRoute: ServicesPoultryProjectReportRoute,
  ServicesPracticalExamCoachingRoute: ServicesPracticalExamCoachingRoute,
  ServicesSheepGoatProjectReportRoute: ServicesSheepGoatProjectReportRoute,
  ServicesVciVeterinaryAdmissionRoute: ServicesVciVeterinaryAdmissionRoute,
  ServicesIndexRoute: ServicesIndexRoute,
}

const ServicesRouteWithChildren = ServicesRoute._addFileChildren(
  ServicesRouteChildren,
)

const rootRouteChildren: RootRouteChildren = {
  IndexRoute: IndexRoute,
  AboutRoute: AboutRoute,
  AdminRoute: AdminRoute,
  BlogRoute: BlogRouteWithChildren,
  ContactRoute: ContactRoute,
  CoursesRoute: CoursesRoute,
  RegisterRoute: RegisterRoute,
  ResultsRoute: ResultsRoute,
  ServicesRoute: ServicesRouteWithChildren,
  AoAaoRoute: AoAaoRoute,
  AoAaoAuthRoute: AoAaoAuthRoute,
  AoAaoCheckoutRoute: AoAaoCheckoutRoute,
  AoAaoPremiumRoute: AoAaoPremiumRoute,
  AoAaoReportSubmissionIdRoute: AoAaoReportSubmissionIdRoute,
  AoAaoTestTestIdRoute: AoAaoTestTestIdRoute,
}
export const routeTree = rootRouteImport
  ._addFileChildren(rootRouteChildren)
  ._addFileTypes<FileRouteTypes>()

import type { getRouter } from './router.tsx'
import type { createStart } from '@tanstack/react-start'
declare module '@tanstack/react-start' {
  interface Register {
    ssr: true
    router: Awaited<ReturnType<typeof getRouter>>
  }
}
